### ISSUE TITLE
是否考虑支持PC版的bilibili播放链接呢

### ISSUE THREAD

**Issue by LeanFly** [Confession1995/spirit#1]

**Comment by Confession1995** [comment]
bilibili电脑端链接目前是支持的  只不过 自己需要添加哔哩两个字  因为目前是按照包含的哔哩和抖音来区分平台开源
例如 哔哩https://xxxxx
![image](https://user-images.githubusercontent.com/39724019/233577169-5bbaf2a2-4989-42f4-bfea-b1e767e53f10.png)

**Comment by Confession1995** [comment]
后续会优化成从链接直接判断平台来源
