### ISSUE TITLE
B站合集类下载只下载第一个

### ISSUE THREAD

**Issue by wustyu** [Confession1995/spirit#4]
收藏夹里面收藏了课程 下载只下了第一p

**Comment by Confession1995** [comment]
目前还没优化多集。包括互动视频也是只能下载第一段，也是后期会优化的内容

**Comment by Confession1995** [comment]
合集类已优化  本周测试完成后上线 。尽情期待

**Comment by wustyu** [comment]
太牛拉



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Zhang XiaoMing ***@***.***&gt;
发送时间: 2023年5月19日 08:46
收件人: Confession1995/spirit ***@***.***&gt;
抄送: jeeyang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Confession1995/spirit] B站合集类下载只下载第一个 (Issue #4)





 
目前还没优化多集。包括互动视频也是只能下载第一段，也是后期会优化的内容
