### ISSUE TITLE
http是可以下载，Aria2不行

### ISSUE THREAD

**Issue by ChanLicher** [Confession1995/spirit#8]
如题，Aria2我自己以前就在用，设置什么的都熟悉，Aria2的内外网的地址都试过了。附上log文件，请大佬帮忙看看。
[error.log](https://github.com/Confession1995/spirit/files/11582897/error.log)
[info.log](https://github.com/Confession1995/spirit/files/11582898/info.log)

顺便提个建议，如果下载能按照来源分类就好了，甚至按照B站的收藏夹名字分类就更好了。

**Comment by Confession1995** [comment]
我看了一下日志 好像没发现啥问题 方便贴一个内网的下载器配置截图吗   如果有token的话 打一下码或者删掉修改成其他字符串在截图    如果是任务能提交到Aria2 但是下载失败  应该是下载路径的问题  如果是无法提交的Aria2 那可能是配置参数的问题  方便问一下Aria2 是http或者https协议 还是强制了https协议之类的吗  如果要是测试的话 推荐单个视频进行测试下载

**Comment by ChanLicher** [comment]
![aria2](https://github.com/Confession1995/spirit/assets/55681496/04666024-b8b3-4182-80e7-677bccf15f4b)
![ariang](https://github.com/Confession1995/spirit/assets/55681496/466d4dfb-5963-48eb-b338-a9bbf6482109)
图一是下载器配置，用的是内网地址，图二是AriaNG的配置界面，内外网都可以使用。我的Aria2用的是host网络，不知道有没有影响，但我在Spirit里内外网都试过了，外网不可以我感觉有可能是因为我开了强制https，但是内网没有强制https。

**Comment by Confession1995** [comment]
我刚重新看了一下你提交的日志   使用docker 部署的 不可以配置127.0.0.1 的地址   直接使用内网再试试,如果是B站和抖音的收藏夹 下载必须添加cookie  如果是单个链接提交可以不填cookie  我在日志中看到有几处异常 是获取的收藏夹是空的 可能是因为cookie的问题  我又瞅了一下我的代码 我也没强制http  应该是可以https的  我刚在docker 的dev 分支上优化了Aria2Util工具类  增加了打印返回信息的日志   可以在看一下是提示什么错误

**Comment by ChanLicher** [comment]
好👌我再试试，谢谢大佬
